package engine

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"math"
	"strings"
	"time"
)

func sp(v float64) string {
	// SPICE engineering notation (meg for 1e6)
	a := math.Abs(v)
	type pf struct {
		m float64
		s string
	}
	for _, p := range []pf{{1e9, "g"}, {1e6, "meg"}, {1e3, "k"}, {1, ""}, {1e-3, "m"}, {1e-6, "u"}, {1e-9, "n"}, {1e-12, "p"}, {1e-15, "f"}} {
		if a >= p.m*0.9995 {
			return strings.TrimSuffix(fmt.Sprintf("%.6g", v/p.m), ".") + p.s
		}
	}
	if v == 0 {
		return "0"
	}
	return fmt.Sprintf("%g", v)
}

func spNode(n string) string {
	if isGround(n) {
		return "0"
	}
	return strings.ReplaceAll(n, ".", "_")
}

// SpiceNetlist exports the complete test set-up (LISNs, filter with
// parasitics, converter noise sources) as a portable SPICE netlist that runs
// in LTspice and ngspice.
func SpiceNetlist(p Params, c *Circuit) string {
	p = Sanitize(p)
	std := GetStandard(p.Standard)
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	w("* EMI input filter - generated by EMI Filter Designer %s", time.Now().Format("2006-01-02 15:04"))
	w("* Mode: %s   Standard: %s   Detector target: %s", strings.ToUpper(p.Mode), std.Name, strings.ToUpper(p.Detector))
	w("* Topology: %s", c.Description)
	w("*")
	w("* Nodes: LM1/LM2 = LISN receiver (50 ohm) outputs; %s/%s = filter input; %s/%s = converter input",
		spNode(c.InTop), spNode(c.InBot), spNode(c.OutTop), spNode(c.OutBot))
	w("* Analysis: AC with unit sources. DM:  .param dm=1 cm=0   CM:  .param dm=0 cm=1")
	w("* Multiply the LISN voltage by the harmonic amplitudes listed at the end to get dBuV.")
	w("*")
	w(".param dm=1 cm=0")
	w("")
	w("* ---- Artificial network(s) (%s) ----", std.LISN)
	lisn := func(node, id string) {
		if std.LISN == "5uH" {
			w("L_LISN%s %s LS%s 5u", id, spNode(node), id)
			w("C_LISNS%s LS%s 0 1u", id, id)
			w("R_LISNS%s LS%s 0 1k", id, id)
			w("R_BAT%s LS%s BAT%s 20m", id, id, id)
			w("L_BAT%s BAT%s 0 0.5u", id, id)
		} else {
			w("L_LISN%s %s LS%s 50u", id, spNode(node), id)
			w("R_LISNS%s LS%s 0 5", id, id)
		}
		w("C_LISN%s %s LM%s 0.1u", id, spNode(node), id)
		w("R_LISNK%s LM%s 0 1k", id, id)
		w("R_LISNM%s LM%s 0 50", id, id)
	}
	lisn(c.InTop, "1")
	if singleLISN(p) {
		w("R_GNDRET %s 0 1m  ; return line grounded locally", spNode(c.InBot))
	} else {
		lisn(c.InBot, "2")
	}
	w("")
	w("* ---- Filter components (with parasitics) ----")
	for _, cp := range c.Comps {
		writeComp(&b, cp)
	}
	w("")
	w("* ---- Converter noise model ----")
	w("I_DM %s %s AC {dm}", spNode(c.OutTop), spNode(c.OutBot))
	w("V_CM SWN %s AC {cm}", spNode(c.OutBot))
	w("C_PAR SWN 0 %s  ; switch node to chassis/PE coupling", sp(p.Cp))
	ops := OpPoints(p)
	if len(ops) > 0 {
		op := ops[0]
		T := 1 / p.Fsw
		w("* For a transient simulation replace the AC sources with (operating point %s):", op.Label)
		if op.Shape == "triangle" {
			w("* I_DM %s %s PULSE(%s %s 0 %s %s 1f %s)", spNode(c.OutTop), spNode(c.OutBot), sp(op.Iin-op.Ripp/2), sp(op.Iin+op.Ripp/2), sp(op.D*T), sp((1-op.D)*T), sp(T))
		} else {
			w("* I_DM %s %s PULSE(0 %s 0 %s %s %s %s)", spNode(c.OutTop), spNode(c.OutBot), sp(op.Ipk), sp(p.RiseTime), sp(p.RiseTime), sp(math.Max(op.D*T-p.RiseTime, 1e-9)), sp(T))
		}
		w("* V_CM SWN %s PULSE(0 %s 0 %s %s %s %s)", spNode(c.OutBot), sp(op.Vsw), sp(p.RiseTime), sp(p.RiseTime), sp(math.Max(op.D*T-p.RiseTime, 1e-9)), sp(T))
	}
	w("")
	w(".ac dec 100 10k %s", sp(std.Fmax))
	w("")
	w("* Harmonic source amplitudes (peak) used by the designer:")
	f, idm, vcm := NoiseSpectrum(p, std.Fmin*0.999, std.Fmax)
	for i := range f {
		if i >= 40 {
			w("* ... (%d more)", len(f)-40)
			break
		}
		w("*  %-10s  Idm = %-10s  Vcm = %s", FmtEng(f[i], "Hz"), sp(idm[i]), sp(vcm[i]))
	}
	w(".end")
	return b.String()
}

func writeComp(b *strings.Builder, c Comp) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }
	q := float64(max(c.Qty, 1))
	desc := c.Role
	if c.Part != nil && c.Part.MPN != "" {
		desc += " - " + c.Part.MPN
	}
	w("* %s: %s%s", c.Ref, desc, map[bool]string{true: fmt.Sprintf(" (%d in parallel)", c.Qty), false: ""}[c.Qty > 1])
	r := strings.ReplaceAll(c.Ref, ".", "_")
	n := func(i int) string { return spNode(c.Nodes[i]) }
	switch c.Kind {
	case "cap":
		x := r + "_x"
		w("R_%s_esr %s %s %s", r, n(0), x, sp(math.Max(c.ESR, 1e-4)/q))
		y := x
		if c.ESL > 0 {
			y = r + "_y"
			w("L_%s_esl %s %s %s", r, x, y, sp(c.ESL/q))
		}
		note := ""
		if c.EffC() != c.Value {
			note = fmt.Sprintf("  ; %s nominal, derated for %gV DC bias", sp(c.Value*q), c.VBias)
		}
		w("C_%s %s %s %s%s", r, y, n(1), sp(c.EffC()*q), note)
	case "res":
		w("R_%s %s %s %s", r, n(0), n(1), sp(c.Value/q))
	case "ind":
		x := r + "_x"
		w("R_%s_dcr %s %s %s", r, n(0), x, sp(math.Max(c.DCR, 1e-5)))
		w("L_%s %s %s %s", r, x, n(1), sp(c.Value))
		if c.SRF > 0 {
			om := 2 * math.Pi * c.SRF
			qs := c.Qsrf
			if qs <= 0 {
				qs = 5
			}
			w("C_%s_par %s %s %s  ; SRF %s", r, x, n(1), sp(1/(om*om*c.Value)), FmtEng(c.SRF, "Hz"))
			w("R_%s_par %s %s %s", r, x, n(1), sp(qs*om*c.Value))
		}
	case "cmc":
		leak := c.Leak
		if leak <= 0 {
			leak = 0.01 * c.Value
		}
		k := math.Min(1-leak/(2*c.Value), 0.99999)
		for i, wd := range []string{"a", "b"} {
			x := r + "_" + wd + "x"
			w("R_%s_dcr%s %s %s %s", r, wd, n(2*i), x, sp(math.Max(c.DCR, 1e-5)))
			w("L_%s_%s %s %s %s", r, wd, x, n(2*i+1), sp(c.Value))
			if c.SRF > 0 {
				om := 2 * math.Pi * c.SRF
				qs := c.Qsrf
				if qs <= 0 {
					qs = 1.5
				}
				w("C_%s_par%s %s %s %s", r, wd, x, n(2*i+1), sp(1/(om*om*c.Value)))
				w("R_%s_par%s %s %s %s", r, wd, x, n(2*i+1), sp(qs*om*c.Value))
			}
		}
		w("K_%s L_%s_a L_%s_b %.6f  ; leakage (DM) %s", r, r, r, k, FmtEng(leak, "H"))
	}
}

// BOMCSV exports the bill of materials.
func BOMCSV(p Params, c *Circuit) string {
	var buf bytes.Buffer
	cw := csv.NewWriter(&buf)
	_ = cw.Write([]string{"Ref", "Qty", "Value", "Function", "Manufacturer", "MPN", "Package", "Rating", "Required",
		"Unit price", "Currency", "Stock", "Source", "Mouser", "DigiKey", "Datasheet"})
	for _, cp := range c.Comps {
		if !cp.InBOM {
			continue
		}
		unit := map[string]string{"cap": "F", "ind": "H", "cmc": "H", "res": "Ω"}[cp.Kind]
		rating, req := "", ""
		switch cp.Kind {
		case "cap":
			if cp.VRated > 0 {
				rating = fmt.Sprintf("%gV%s %s", cp.VRated, map[bool]string{true: "AC", false: ""}[cp.ReqVAC], cp.Class)
			}
			if cp.ReqV > 0 {
				req = fmt.Sprintf("≥%gV%s", math.Round(cp.ReqV), map[bool]string{true: "AC", false: ""}[cp.ReqVAC])
			}
		case "ind", "cmc":
			if lp, ok := libByMPN(partMPN(cp)); ok {
				rating = fmt.Sprintf("Irms %gA", lp.IRms)
				if lp.ISat > 0 {
					rating += fmt.Sprintf(", Isat %gA", lp.ISat)
				}
				rating += ", DCR " + FmtEng(lp.DCR, "Ω")
			}
			req = fmt.Sprintf("Irms ≥ %.2gA", cp.ReqI)
			if cp.ReqIsat > 0 {
				req += fmt.Sprintf(", Isat ≥ %.2gA", cp.ReqIsat)
			}
		case "res":
			rating = cp.Package
		}
		pi := cp.Part
		if pi == nil {
			pi = &PartInfo{}
		}
		price := ""
		if pi.UnitPrice > 0 {
			price = fmt.Sprintf("%.4g", pi.UnitPrice)
		}
		stock := ""
		if pi.Stock > 0 {
			stock = fmt.Sprint(pi.Stock)
		}
		_ = cw.Write([]string{cp.Ref, fmt.Sprint(max(cp.Qty, 1)), FmtEng(cp.Value, unit), cp.Role, pi.Manufacturer, pi.MPN, cp.Package,
			rating, req, price, pi.Currency, stock, pi.Source, pi.MouserURL, pi.DigikeyURL, pi.DatasheetURL})
	}
	cw.Flush()
	return buf.String()
}

func partMPN(c Comp) string {
	if c.Part == nil {
		return ""
	}
	return c.Part.MPN
}
